# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.db.models.deletion
from django.db import migrations, models

import apps.core.file_security
import apps.resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50, verbose_name='icon name')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'resource category',
                'verbose_name_plural': 'resource categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('lecture_note', 'Lecture Notes'), ('pdf', 'PDF Document'), ('book', 'Book'), ('slides', 'Presentation Slides'), ('assignment', 'Assignment / Exercise'), ('template', 'Template'), ('dataset', 'Research Data / Dataset'), ('video', 'Video'), ('external', 'External Link'), ('other', 'Other')], db_index=True, default='other', max_length=30, verbose_name='type')),
                ('author', models.CharField(blank=True, max_length=300, verbose_name='author')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='tags')),
                ('version', models.CharField(blank=True, default='1.0', max_length=20, verbose_name='version')),
                ('language', models.CharField(default='Lao', max_length=50, verbose_name='language')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.resources.models.resource_file_path, validators=[apps.core.file_security.validate_file_extension, apps.core.file_security.validate_file_size, apps.core.file_security.validate_file_mime], verbose_name='file')),
                ('file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='file size (bytes)')),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='file SHA-256')),
                ('external_url', models.URLField(blank=True, verbose_name='external URL')),
                ('visibility', models.CharField(choices=[('public', 'Public — anyone can access'), ('students', 'Students Only'), ('private', 'Private — admin only')], db_index=True, default='public', max_length=20, verbose_name='visibility')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='downloads')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_resources', to='courses.course')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'visibility'], name='resources_r_resourc_0c88fa_idx'), models.Index(fields=['visibility', 'is_featured'], name='resources_r_visibil_fc8257_idx')],
            },
        ),
    ]
