# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='tag')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='OG image')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='subtitle')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='excerpt')),
                ('content_raw', models.TextField(help_text='Raw HTML from editor. Will be sanitized on save.', verbose_name='content (raw)')),
                ('content', models.TextField(editable=False, help_text='Auto-sanitized HTML.', verbose_name='content (sanitized)')),
                ('category', models.CharField(choices=[('article', 'Article'), ('announcement', 'Announcement'), ('academic', 'Academic Writing'), ('news', 'News'), ('tutorial', 'Tutorial')], db_index=True, default='article', max_length=30, verbose_name='category')),
                ('thumbnail', models.TextField(blank=True, max_length=100, null=True, verbose_name='thumbnail')),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='reading time (min)')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='allow comments')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical article',
                'verbose_name_plural': 'historical articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG image')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='subtitle')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='excerpt')),
                ('content_raw', models.TextField(help_text='Raw HTML from editor. Will be sanitized on save.', verbose_name='content (raw)')),
                ('content', models.TextField(editable=False, help_text='Auto-sanitized HTML.', verbose_name='content (sanitized)')),
                ('category', models.CharField(choices=[('article', 'Article'), ('announcement', 'Announcement'), ('academic', 'Academic Writing'), ('news', 'News'), ('tutorial', 'Tutorial')], db_index=True, default='article', max_length=30, verbose_name='category')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnails/', verbose_name='thumbnail')),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='reading time (min)')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='views')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='allow comments')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.articletag')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='blog_articl_status_397c47_idx'), models.Index(fields=['status', 'is_featured'], name='blog_articl_status_8ba078_idx')],
            },
        ),
    ]
