# Generated by Django 5.2.17 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_article_og_image_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["status", "published_at"], name="blog_articl_status_8b18ca_idx"
            ),
        ),
    ]
