# Generated by Django 5.1.4 on 2026-09-21 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=255, verbose_name='path')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('referer', models.URLField(blank=True, max_length=512, verbose_name='referer')),
                ('is_authenticated', models.BooleanField(default=False, verbose_name='authenticated')),
            ],
            options={
                'verbose_name': 'page view',
                'verbose_name_plural': 'page views',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path', 'timestamp'], name='analytics_p_path_51c7b7_idx')],
            },
        ),
    ]
