# Generated by Django 5.1.4 on 2026-09-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=300, verbose_name='subject')),
                ('message', models.TextField(max_length=5000, verbose_name='message')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='organization')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
