[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
python_files = tests.py test_*.py *_tests.py
testpaths = tests
addopts = --nomigrations -p no:warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::django.utils.deprecation.RemovedInDjango51Warning
markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow running tests
