# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_failure', 'Login Failure'), ('account_locked', 'Account Locked'), ('ip_blocked', 'IP Blocked'), ('brute_force', 'Brute Force Detected'), ('file_rejected', 'File Upload Rejected'), ('permission_denied', 'Permission Denied'), ('csrf_failure', 'CSRF Failure'), ('rate_limited', 'Rate Limited'), ('suspicious', 'Suspicious Activity')], db_index=True, max_length=50, verbose_name='event type')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='request path')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('resolved', models.BooleanField(default=False, verbose_name='resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
            ],
            options={
                'verbose_name': 'security event',
                'verbose_name_plural': 'security events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='security_se_event_t_1a00f0_idx'), models.Index(fields=['ip_address', 'timestamp'], name='security_se_ip_addr_7e6b32_idx'), models.Index(fields=['severity', 'resolved'], name='security_se_severit_d0a5b5_idx')],
            },
        ),
    ]
