# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG image')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('guest_lecture', 'Guest Lecture'), ('webinar', 'Webinar'), ('other', 'Other')], db_index=True, default='seminar', max_length=30, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=400, verbose_name='location')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='is virtual')),
                ('registration_link', models.URLField(blank=True, verbose_name='registration link')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='cover image')),
                ('organizer', models.CharField(blank=True, max_length=300, verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-start_time', '-created_at'],
                'indexes': [models.Index(fields=['status', 'start_time'], name='events_even_status_189ced_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='OG image')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('guest_lecture', 'Guest Lecture'), ('webinar', 'Webinar'), ('other', 'Other')], db_index=True, default='seminar', max_length=30, verbose_name='type')),
                ('description', models.TextField(verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=400, verbose_name='location')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='is virtual')),
                ('registration_link', models.URLField(blank=True, verbose_name='registration link')),
                ('start_time', models.DateTimeField(db_index=True, verbose_name='start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='end time')),
                ('cover_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='cover image')),
                ('organizer', models.CharField(blank=True, max_length=300, verbose_name='organizer')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical event',
                'verbose_name_plural': 'historical events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
