# Generated by Django 5.2.17 on 2026-09-22 17:35

import apps.core.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="events/covers/",
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="cover image",
            ),
        ),
        migrations.AlterField(
            model_name="historicalevent",
            name="cover_image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="cover image",
            ),
        ),
    ]
