# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='Snapshot of user email at time of action.', max_length=254, verbose_name='user email')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('mfa_setup', 'MFA Setup'), ('mfa_verified', 'MFA Verified'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('unpublish', 'Unpublish'), ('archive', 'Archive'), ('restore', 'Restore'), ('user_created', 'User Created'), ('user_deactivated', 'User Deactivated'), ('role_changed', 'Role Changed'), ('permission_changed', 'Permission Changed'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_delete', 'File Delete'), ('account_locked', 'Account Locked'), ('ip_blocked', 'IP Blocked')], db_index=True, max_length=50, verbose_name='action')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='object ID')),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the affected object at time of action.', max_length=255, verbose_name='object representation')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='request path')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='request method')),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('error', 'Error')], db_index=True, default='success', max_length=20, verbose_name='result')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='extra data')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['action', 'timestamp'], name='audit_audit_action_2a1328_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx')],
            },
        ),
    ]
