# Generated by Django 5.1.4 on 2026-09-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="object ID"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_repr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="String representation of the affected object at time of action.",
                max_length=255,
                verbose_name="object representation",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_method",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="request method"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="request path"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_agent",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="user agent"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Snapshot of user email at time of action.",
                max_length=254,
                verbose_name="user email",
            ),
        ),
    ]
