# Generated by Django 5.2.17 on 2026-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_description_alter_auditlog_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("login_failed", "Login Failed"),
                    ("password_change", "Password Change"),
                    ("mfa_setup", "MFA Setup"),
                    ("mfa_verified", "MFA Verified"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("publish", "Publish"),
                    ("unpublish", "Unpublish"),
                    ("archive", "Archive"),
                    ("restore", "Restore"),
                    ("user_created", "User Created"),
                    ("user_activated", "User Activated"),
                    ("user_deactivated", "User Deactivated"),
                    ("role_changed", "Role Changed"),
                    ("permission_changed", "Permission Changed"),
                    ("file_upload", "File Upload"),
                    ("file_download", "File Download"),
                    ("file_delete", "File Delete"),
                    ("account_locked", "Account Locked"),
                    ("ip_blocked", "IP Blocked"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="action",
            ),
        ),
    ]
