# Generated by Django 5.2.17 on 2026-09-22 17:35

from django.db import migrations, models

import apps.core.file_security


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpublication",
            name="pdf_file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="publications/pdfs/",
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="PDF",
            ),
        ),
    ]
