# Generated by Django 5.2.17 on 2026-09-28 09:35

import apps.core.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0002_alter_historicalpublication_pdf_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpublication",
            name="og_image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="OG image",
            ),
        ),
        migrations.AlterField(
            model_name="historicalresearchproject",
            name="og_image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="OG image",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seo/og/",
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="OG image",
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seo/og/",
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="OG image",
            ),
        ),
    ]
