# Generated by Django 5.2.17 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0003_alter_historicalpublication_og_image_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="publication",
            name="research_pu_doi_a02bf2_idx",
        ),
        migrations.AddIndex(
            model_name="researchproject",
            index=models.Index(
                fields=["status", "research_status"],
                name="research_re_status_5e7573_idx",
            ),
        ),
    ]
