# Generated by Django 5.2.17 on 2026-09-29 15:52

import apps.assistant.models
import apps.core.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="title")),
                ("slug", models.SlugField(blank=True, max_length=320, unique=True)),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="summary"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Paste FAQ / policy / course info here. Searched by the AI.",
                        verbose_name="knowledge text",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Optional. .txt/.md are auto-indexed; .pdf needs text pasted above.",
                        null=True,
                        upload_to=apps.assistant.models.knowledge_file_path,
                        validators=[
                            apps.core.file_security.validate_file_extension,
                            apps.core.file_security.validate_file_size,
                            apps.core.file_security.validate_file_mime,
                        ],
                        verbose_name="supporting file (txt/md/pdf)",
                    ),
                ),
                (
                    "file_text",
                    models.TextField(
                        blank=True, editable=False, verbose_name="extracted file text"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="tags",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("lo", "ລາວ")],
                        default="en",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="source link")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="active (visible to AI)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "knowledge document",
                "verbose_name_plural": "knowledge documents (AI Knowledge Box)",
                "ordering": ["-updated_at"],
            },
        ),
    ]
