# Generated by Django 5.1.4 on 2026-09-29 16:17

import apps.assistant.models
import apps.core.file_security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0002_seed_faqs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgedocument",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional. .txt/.md/.pdf text is auto-indexed for the AI.",
                null=True,
                upload_to=apps.assistant.models.knowledge_file_path,
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="supporting file (txt/md/pdf)",
            ),
        ),
    ]
