# Generated by Django 5.1.4 on 2026-09-21 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='professional title')),
                ('short_bio', models.TextField(blank=True, max_length=500, verbose_name='short bio')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('office', models.CharField(blank=True, max_length=200, verbose_name='office location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('orcid', models.CharField(blank=True, max_length=50, verbose_name='ORCID')),
                ('google_scholar_url', models.URLField(blank=True, verbose_name='Google Scholar')),
                ('researchgate_url', models.URLField(blank=True, verbose_name='ResearchGate')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.CharField(max_length=200, verbose_name='organization')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='role')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='since')),
                ('is_current', models.BooleanField(default=True, verbose_name='current')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'organization'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='language')),
                ('proficiency', models.CharField(choices=[('native', 'Native'), ('fluent', 'Fluent'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate'), ('basic', 'Basic')], max_length=20, verbose_name='proficiency')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='profiles.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('position', models.CharField(max_length=200, verbose_name='position')),
                ('organization', models.CharField(max_length=300, verbose_name='organization')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='department')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='start year')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='end year')),
                ('is_current', models.BooleanField(default=False, verbose_name='current')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.profile')),
            ],
            options={
                'ordering': ['-year_end', '-year_start'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('degree', models.CharField(max_length=200, verbose_name='degree')),
                ('field', models.CharField(max_length=200, verbose_name='field of study')),
                ('institution', models.CharField(max_length=300, verbose_name='institution')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('year_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='start year')),
                ('year_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='end year')),
                ('is_current', models.BooleanField(default=False, verbose_name='current')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile')),
            ],
            options={
                'ordering': ['-year_end', '-year_start', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('issuer', models.CharField(max_length=200, verbose_name='issuer')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('expiry_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='expiry year')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='credential ID')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential URL')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.profile')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='award name')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='organization')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='year')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='profiles.profile')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='AcademicInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='interest')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='profiles.profile')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
