# Generated by Django 5.2.17 on 2026-09-22 17:35

from django.db import migrations, models

import apps.core.file_security


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile/",
                validators=[
                    apps.core.file_security.validate_file_extension,
                    apps.core.file_security.validate_file_size,
                    apps.core.file_security.validate_file_mime,
                ],
                verbose_name="photo",
            ),
        ),
    ]
