# Generated by Django 5.1.4 on 2026-09-21 23:32

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import apps.core.file_security
import apps.courses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og/', verbose_name='OG image')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='course code')),
                ('name', models.CharField(max_length=300, verbose_name='course name')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='short description')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='credits')),
                ('semester', models.CharField(blank=True, max_length=50, verbose_name='semester')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='academic year')),
                ('level', models.CharField(blank=True, help_text='e.g. Undergraduate, Graduate, PhD', max_length=50, verbose_name='level')),
                ('language', models.CharField(default='Lao', max_length=50, verbose_name='language of instruction')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/', verbose_name='thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('enrolled', 'Enrolled Students Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-academic_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'course category',
                'verbose_name_plural': 'course categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.course')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='week number')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True, verbose_name='visible to students')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'course module',
                'ordering': ['order', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('slides', 'Slides'), ('video', 'Video'), ('link', 'External Link'), ('dataset', 'Dataset'), ('other', 'Other')], default='other', max_length=20, verbose_name='type')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.courses.models.resource_upload_path, validators=[apps.core.file_security.validate_file_extension, apps.core.file_security.validate_file_size, apps.core.file_security.validate_file_mime], verbose_name='file')),
                ('external_url', models.URLField(blank=True, verbose_name='external URL')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('students', 'Students Only'), ('private', 'Private')], default='students', max_length=20, verbose_name='visibility')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.coursemodule')),
            ],
            options={
                'verbose_name': 'course resource',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnnouncement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.course')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical announcement',
                'verbose_name_plural': 'historical announcements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('slug', models.SlugField(help_text='URL-friendly identifier. Auto-generated from title.', max_length=255, verbose_name='slug')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO description')),
                ('seo_keywords', models.CharField(blank=True, max_length=255, verbose_name='SEO keywords')),
                ('og_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='OG image')),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='course code')),
                ('name', models.CharField(max_length=300, verbose_name='course name')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='short description')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='credits')),
                ('semester', models.CharField(blank=True, max_length=50, verbose_name='semester')),
                ('academic_year', models.CharField(blank=True, max_length=20, verbose_name='academic year')),
                ('level', models.CharField(blank=True, help_text='e.g. Undergraduate, Graduate, PhD', max_length=50, verbose_name='level')),
                ('language', models.CharField(default='Lao', max_length=50, verbose_name='language of instruction')),
                ('thumbnail', models.TextField(blank=True, max_length=100, null=True, verbose_name='thumbnail')),
                ('featured', models.BooleanField(default=False, verbose_name='featured')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('enrolled', 'Enrolled Students Only'), ('private', 'Private')], default='public', max_length=20, verbose_name='visibility')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courses.coursecategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course',
                'verbose_name_plural': 'historical courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('description', models.CharField(max_length=500, verbose_name='outcome')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'featured'], name='courses_cou_status_c6495b_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='courses_cou_code_612388_idx'),
        ),
    ]
