# Generated by Django 5.2.17 on 2026-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_course_og_image_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["status", "visibility"], name="courses_cou_status_04f379_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseresource",
            index=models.Index(
                fields=["course", "visibility"], name="courses_cou_course__466496_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseresource",
            index=models.Index(
                fields=["module", "visibility"], name="courses_cou_module__425c98_idx"
            ),
        ),
    ]
