# Generated by Django 5.2.17 on 2026-09-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teaching", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officehours",
            options={
                "ordering": ["start_time"],
                "verbose_name": "office hours",
                "verbose_name_plural": "office hours",
            },
        ),
        migrations.AlterModelOptions(
            name="teachingphilosophy",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "teaching philosophy",
                "verbose_name_plural": "teaching philosophies",
            },
        ),
    ]
